# Generated by Django 3.2.19 on 2023-06-06 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230606_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.user'),
        ),
    ]
