# Generated by Django 3.2.19 on 2023-06-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscstats',
            name='external_users_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miscstats',
            name='internal_users_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miscstats',
            name='quotum_total',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miscstats',
            name='size_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='miscstats',
            name='users_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectstats',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
