# Generated by Django 3.2.19 on 2023-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
