version: '3'

services:
  adminrd-web:
    container_name: adminrd-web
    #restart: always
    build:
      context: .
      args:
        - APP_USER_UID=${USER_UID}
        - APP_USER_GID=${USER_GID}
    user: ${USER_UID}:${USER_GID}
    depends_on:
      adminrd-db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      SITE_NAME: 127.0.0.1
      SECRET: ${SECRET}
    ports:
      - "8001:8000"
    volumes:
      - .:/usr/src/app
      - /docker/adminrd/log:/usr/app/log

  adminrd-task:
    container_name: adminrd-task
    build:
      context: .
      args:
        - APP_USER_UID=${USER_UID}
        - APP_USER_GID=${USER_GID}
    user: ${USER_UID}:${USER_GID}
    depends_on:
      adminrd-db:
        condition: service_healthy
    environment:
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DATADIR: /data
      SITE_NAME: adminrd.labs.vu.nl
      SECRET: ${SECRET}
    command: python manage.py qcluster
    volumes:
      - .:/usr/src/app
      - /docker/adminrd/log:/usr/app/log
      - ${DATASRC}:/data:rw

  adminrd-db:
    container_name: ${DB_HOST}
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /docker/adminrd/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U django"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - adminrd-web
    ports:
      - "8081:80"
    volumes:
      - ./static:/static:ro  # for syncing with django source code
      - ./nginx_conf:/etc/nginx/conf.d:ro